source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Leaflet_Example', :exclusive => true do
  pod "Leaflet", :path => "../"
end

target 'Leaflet_Tests', :exclusive => true do
  pod "Leaflet", :path => "../"

  
end
