source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Leaflet_Example' do
  pod "Leaflet", :path => "../"
end

target 'Leaflet_Tests' do
  pod "Leaflet", :path => "../"
end
